### ISSUE TITLE
How is the rate of pullind determined in a  steered simulation?

### ISSUE THREAD

**Issue by sperezconesa** [delemottelab/string-method-gmxapi#14]
Hello Oliver,

How is the rate of pulling determined? Does it just depend on the number of steps in steered.mdp?

Thanks,
Sergio

**Comment by oliverfleetwood** [comment]
It depends on two input files with some parameters:

**steered.mpd**
 the number of steps and the step size. This gives you the time to pull in picoseconds between two points. 

**string0.txt (i.e. the input pathway defined in config.json""
 The CV values of two adjacent points. The script will find the difference between the two points. The pull rate is this value divided by the simulation time.

**Comment by oliverfleetwood** [comment]
Closing this issue since it's not an issue but rather a question. It's not critical for the user to know either
